FROM node:20-alpine
RUN apk add --no-cache postgresql-client
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npx prisma generate && npm run build
RUN npm prune --production && npx prisma generate
EXPOSE 3100
CMD ["node", "dist/app.js"]
